name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: mohit2004/pckd-server:latest
      -
        name: Build and push
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: mohit2004/pckd-client:latest
